# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Azure CAF Launchpad Destroy $(Major).$(Minor).$(Patch)

variables:
- name: Major
  value: '1'
- name: Minor
  value: '0'
- name: Patch
  value: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 0)]
- name: ProjectName
  value: AzureCAF
- name: CompanyName
  value: Demo
- name: Environment
  value: Test
- group: 'CAFLaunhpadCanary'

trigger: none

resources:
  repositories:
    - repository: CAF_LandingZones
      type: git
      name: COE/caf-terraform-landingzones
  containers:
  - container: rover
    image: $(ROVER_IMAGE)
    options: --user 0:0 -e TF_PLUGIN_CACHE_DIR="/home/$(ROVER_HOME_DIR)/plugin-cache" -e TF_DATA_DIR="/home/$(ROVER_HOME_DIR)"

stages:
- stage: Destroy
  jobs:
  - job: waitForValidation
    displayName: "Confirm You want to Destroy Launhpad"
    continueOnError: 'false'
    pool: server
    timeoutInMinutes: '2880' ## 2 day
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        instructions: "Confirm You want to Destroy Launhpad"
        onTimeout: reject
        notifyUsers: $(LAUNCHPAD_PLAN_APPROVERS)
  
  - job: LaunhpadDestroy
    displayName: "Launchad Destroy"
    dependsOn: "waitForValidation"
    pool: 
      vmImage: 'ubuntu-latest'
    continueOnError: 'false'
    workspace:
          clean: all
    container: rover
    timeoutInMinutes: '600'
    steps:
    - checkout: self   
    - checkout: CAF_LandingZones 
    - bash: |
        sudo mv aztf-caf-level0-launchpad /tf/caf/aztf-caf-level0-launchpad -f
        sudo mv caf-terraform-landingzones /tf/caf/caf-terraform-landingzones -f
      failOnStderr: 'true'
      displayName: 'Checkout'

    - bash: |
        az login --service-principal --username $(CAF_LAUNCHPAD_SP_CLIENTID) --password $(CAF_LAUNCHPAD_SP_SECRET) --tenant $(LAUNCHPAD_TENANTID)
        az account set --subscription $(LAUNCHPAD_SUBSCRIPTION_ID)
      failOnStderr: 'true'
      displayName: 'Login to Azure'

    - bash: |
        git config --global user.name "$(CAF_Terraform_Module_User)"
        git config --global url."https://oauth2:$(CAF_Terraform_Module_Token)@dev.azure.com/Cloud-Studio-Org/COE/_git/caf-terraform-modules".insteadOf https://dev.azure.com/Cloud-Studio-Org/COE/_git/caf-terraform-modules

        /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/caf_launchpad \
        -tfstate $(LAUNCHPAD_TFSTATE_FILE) \
        -var-folder /tf/caf/aztf-caf-level0-launchpad/configuration/$(CAF_ENV) \
        -parallelism=30 \
        -env $(CAF_ENV) \
        -launchpad \
        -a destroy
      failOnStderr: 'true'
      displayName: 'Terraform Launchpad Deploy'