pipeline {
  agent {
    docker {
      image 'aztfmod/rover:1.0.1-2106.3012'
      args "--env HTTP_PROXY=http:/${env.PROXY} --env HTTPS_PROXY=http://${env.PROXY}"
      label 'aztf-caf'
    }
  }

  options {
    timestamps()
    skipDefaultCheckout()
  }

  environment {
    ROVER_RUNNER = true
    TF_REGISTRY_CLIENT_TIMEOUT = 30
    TF_REGISTRY_DISCOVERY_RETRY = 30
    TF_CLI_ARGS_destroy = '-auto-approve -refresh=false'
    TF_LOG = "${env.LOG_LEVEL ? (env.LOG_LEVEL == 'DEFAULT' ? '' : env.LOG_LEVEL) : ''}"
  }

  stages {
    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: "${env.CONFIG_REPO_BRANCH}"]], userRemoteConfigs: [[credentialsId: "aztf-caf-github-pat-level0", url: "https://github.com/cloud-studio-repository-org/aztf-caf-level0-launchpad.git"]]])
        checkout([$class: 'GitSCM', branches: [[name: "${env.LOGIC_REPO_BRANCH}"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "landingzones"]], userRemoteConfigs: [[credentialsId: "aztf-caf-github-pat-level0", url: "https://github.com/cloud-studio-repository-org/caf-terraform-landingzones.git"]]])
      }
    }

    stage('Rover Login') {
      steps {
        ansiColor('xterm') {
          sh """
            /tf/rover/rover.sh login --tenant ${env.TENANT_ID} --subscription ${env.SUBSCRIPTION_ID}
          """
        }
      }
    }

    stage('Approve'){
      steps {
        timeout(time: 72, unit: 'HOURS') {
          input (message: "OK to destroy all the infrastruture in the Launchpad LZ at level 0?")
        }
      }
    }

    stage('Destroy') {
      steps {
        ansiColor('xterm') {
          sh """
            /tf/rover/rover.sh -lz ${env.WORKSPACE}/landingzones/caf_launchpad -tfstate launchpad.tfstate -var-folder ${env.WORKSPACE}/configuration/${env.ROVER_ENV} -parallelism 10 -level level0 -env ${env.ROVER_ENV} -launchpad -a destroy
          """
        }
      }
    }
  }
}
