apiVersion: apps/v1
kind: Deployment
metadata:
  name: level0
  labels:
    app: level0
  namespace: level0
spec:   
  selector:
    matchLabels:
      app: level0
  template:
    metadata:
      labels:
        app: level0
        version: v1
    spec:
      replicas: 3
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      containers:
        - name: level0
          image: thiruazure2labacr.azurecr.io/custom1aksnginxapp1:32
          ports:
            - containerPort: 8090
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
          seccompProfile:
            type: RuntimeDefault